project:
  type: website

website:
  site-url: "https://ubvu.github.io/bytes-and-bites/"
  title: "Bytes & Bites"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: events.qmd
        text: Events
      - text: Learn  
        menu:
        - text: Info
          href: learning_files/info.qmd
        - text: Resources
          href: learning_files/resources.qmd
        - text: Tools
          href: learning_files/tools.qmd
      - href: eat.qmd
        text: Eat
      - href: news.qmd
        text: News
    tools:
      - icon: github
        href: https://github.com/ubvu/bytes-and-bites/tree/main


format:
  html:
    theme: journal
    css: styles.css
    toc: true



