project:
  type: website

website:
  site-url: "https://ubvu.github.io/bytes-and-bites/"
  title: "Bytes & Bites"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: journal
    css: styles.css
    toc: true



